In [1]:
import requests
from bs4 import BeautifulSoup
import pprint
import pandas as pd

def GetdataList(tr_tags):
    rowLis = []
    dataLis = []
    for i in range(4,24):
        rows = tr_tags[i].find_all('td')
        for row in rows:
            dataLis.append(row.text)
        rowLis.append(dataLis)
        dataLis=[]
    return rowLis

In [15]:
#URLを取得
List = [0, 20, 40, 60, 80]
trLis = []
SumLis = []
y = 0
for x in List:
    url = ('https://www.boki-teacher.com/tokyo/su3_list.cgi?'
        f'action=showlast&cat=&txtnumber=log&next_page={x}'
        '&t_type=list&sort=117&reverse=')

    r = requests.get(url)
    soup = BeautifulSoup(r.content, 'html.parser')
    tr_tags = soup.find_all('tr')

    #テーブル先頭行を取得（最初のページのみ）
    if x == 0:
        columnsLis = []
        tds = tr_tags[3].find_all('td') 
        for td in tds:
            columnsLis.append(td.text)

    trLis = GetdataList(tr_tags)
    SumLis.extend(trLis)

In [17]:
df = pd.DataFrame(SumLis,columns =columnsLis)
df = df.drop(['E-mail', 'No.'], axis=1)
df = df.rename(columns={'名前（ハンドルネーム）': 'Name'})

In [18]:
df

      Name  性別   年齢   居住地   希望時給   合格済みの簿記系資格         登録日
0       リサ  女性  20歳  世田谷区  1000円       日商簿記2級  2019/09/18
1    吉田 久将  男性  23歳   中央区  1500円  税理士・簿財（2科目）  2019/09/20
2   すぺらんかー  男性  29歳  千代田区  2000円       日商簿記1級  2019/09/21
3      ヤマダ  男性  28歳   品川区  1500円        公認会計士  2019/09/21
4       YA  男性  33歳  武蔵野市  5000円       日商簿記2級  2019/09/22
..     ...  ..  ...   ...    ...          ...         ...
95      かな  女性  27歳    北区  2000円       日商簿記1級  2022/04/17
96      かな  女性  27歳    北区  2000円       日商簿記1級  2022/04/17
97      井上  女性  27歳   墨田区  1100円       日商簿記2級  2022/05/09
98     かずお  男性  22歳   葛飾区  1100円       日商簿記1級  2022/05/10
99      AS  男性  33歳   渋谷区  2500円        公認会計士  2022/06/07

[100 rows x 7 columns]

In [19]:
df_w = df[df['性別'] == '女性']
df_w

          Name  性別   年齢   居住地   希望時給   合格済みの簿記系資格         登録日
0           リサ  女性  20歳  世田谷区  1000円       日商簿記2級  2019/09/18
8           ゆん  女性  20歳  千代田区  2000円       日商簿記2級  2019/10/06
13          北村  女性  24歳   江東区  1600円       日商簿記1級  2019/11/06
14          mk  女性  30歳   台東区  1000円       日商簿記1級  2019/11/23
19          井上  女性  26歳   文京区  1800円       日商簿記2級  2020/01/17
26           K  女性  26歳    北区  2500円        公認会計士  2020/03/10
27        てらみな  女性  26歳   文京区  1000円        公認会計士  2020/03/19
33          優里  女性  20歳    北区  1500円       日商簿記2級  2020/05/11
38       カナチャン  女性  26歳    北区  2000円       日商簿記1級  2020/06/22
42        簿記ねこ  女性  47歳  世田谷区  1500円       日商簿記2級  2020/08/28
43          井上  女性  25歳   墨田区  1000円       日商簿記2級  2020/10/19
55        井上美樹  女性  25歳   墨田区  1200円       日商簿記2級  2021/03/08
63          るか  女性  23歳  千代田区  2500円        公認会計士  2021/05/13
66          ゆず  女性  18歳   多摩市  1500円       日商簿記3級  2021/06/15
67         みかん  女性  35歳   豊島区  2000円       日商簿記2級  2021/06/17
70         ここも  女性  19歳    港区  1100円       日商簿記2級  2021/07/09
81  旧姓山崎:建設2級も  女性  48歳   練馬区  2500円  税理士・簿財（2科目）  2021/10/24
86          みく  女性  29歳   足立区  1000円       日商簿記3級  2021/11/28
90       川口ちひろ  女性  19歳  八王子市  1300円      税理士・簿記論  2022/01/27
93          なな  女性  21歳   文京区  2000円       日商簿記1級  2022/02/13
95          かな  女性  27歳    北区  2000円       日商簿記1級  2022/04/17
96          かな  女性  27歳    北区  2000円       日商簿記1級  2022/04/17
97          井上  女性  27歳   墨田区  1100円       日商簿記2級  2022/05/09

In [20]:
df_w = df_w.sort_values('年齢')
df_w

          Name  性別   年齢   居住地   希望時給   合格済みの簿記系資格         登録日
66          ゆず  女性  18歳   多摩市  1500円       日商簿記3級  2021/06/15
90       川口ちひろ  女性  19歳  八王子市  1300円      税理士・簿記論  2022/01/27
70         ここも  女性  19歳    港区  1100円       日商簿記2級  2021/07/09
0           リサ  女性  20歳  世田谷区  1000円       日商簿記2級  2019/09/18
8           ゆん  女性  20歳  千代田区  2000円       日商簿記2級  2019/10/06
33          優里  女性  20歳    北区  1500円       日商簿記2級  2020/05/11
93          なな  女性  21歳   文京区  2000円       日商簿記1級  2022/02/13
63          るか  女性  23歳  千代田区  2500円        公認会計士  2021/05/13
13          北村  女性  24歳   江東区  1600円       日商簿記1級  2019/11/06
43          井上  女性  25歳   墨田区  1000円       日商簿記2級  2020/10/19
55        井上美樹  女性  25歳   墨田区  1200円       日商簿記2級  2021/03/08
38       カナチャン  女性  26歳    北区  2000円       日商簿記1級  2020/06/22
27        てらみな  女性  26歳   文京区  1000円        公認会計士  2020/03/19
26           K  女性  26歳    北区  2500円        公認会計士  2020/03/10
19          井上  女性  26歳   文京区  1800円       日商簿記2級  2020/01/17
96          かな  女性  27歳    北区  2000円       日商簿記1級  2022/04/17
95          かな  女性  27歳    北区  2000円       日商簿記1級  2022/04/17
97          井上  女性  27歳   墨田区  1100円       日商簿記2級  2022/05/09
86          みく  女性  29歳   足立区  1000円       日商簿記3級  2021/11/28
14          mk  女性  30歳   台東区  1000円       日商簿記1級  2019/11/23
67         みかん  女性  35歳   豊島区  2000円       日商簿記2級  2021/06/17
42        簿記ねこ  女性  47歳  世田谷区  1500円       日商簿記2級  2020/08/28
81  旧姓山崎:建設2級も  女性  48歳   練馬区  2500円  税理士・簿財（2科目）  2021/10/24

In [23]:
df_w.to_csv('Bokki.csv',encoding='shift-jis')